name: .NET 8.0 CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Release --no-restore

    # Шаг для проверки структуры папок
    - name: Verify build output
      run: |
        $buildOutput = Get-ChildItem -Path . -Recurse -Include *.dll,*.pdb
        Write-Host "Build output files:"
        $buildOutput | ForEach-Object { Write-Host $_.FullName }
        if (-not $buildOutput) {
            Write-Error "No build output files found!"
            exit 1
        }

    # Альтернативный способ запуска тестов
    - name: Run tests
      run: |
        # Пробуем несколько способов запуска тестов
        Write-Host "Attempt 1: dotnet test on solution"
        dotnet test --configuration Release --no-build --logger "console;verbosity=normal" || (
            Write-Host "Attempt 1 failed, trying alternative approach..."
            
            Write-Host "Attempt 2: Find and run test project directly"
            $testProj = Get-ChildItem -Path . -Recurse -Filter *.csproj | 
                        Where-Object { $_.FullName -like "*TestProject1*" } | 
                        Select-Object -First 1
            
            if ($testProj) {
                Write-Host "Found test project at: $($testProj.FullName)"
                dotnet test $testProj.FullName --configuration Release --logger "console;verbosity=normal"
            } else {
                Write-Error "Test project not found!"
                exit 1
            }
        )
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: TestResults/