name: .NET Framework Tests

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Install Test Components
      run: |
        choco install visualstudio2022-testagent -y --no-progress
        choco install visualstudio2022-workload-webbuildtools -y --no-progress

    - name: Restore NuGet packages
      run: nuget restore WindowsFormsApp1.sln

    - name: Build solution
      run: msbuild WindowsFormsApp1.sln /p:Configuration=Debug

    - name: Find and Run Tests
      shell: pwsh
      run: |
        # 1. Находим vstest.console.exe
        $vstestPath = (Get-ChildItem -Path "${env:ProgramFiles(x86)}\Microsoft Visual Studio" -Recurse -Filter "vstest.console.exe" | Select-Object -First 1).FullName
        
        if (-not $vstestPath) {
            throw "vstest.console.exe not found!"
        }
        
        Write-Host "Found vstest at: $vstestPath"
        
        # 2. Проверяем существование тестовой DLL
        $testDll = "UnitTestProject1\bin\Debug\UnitTestProject1.dll"
        if (-not (Test-Path $testDll)) {
            throw "Test DLL not found at: $testDll"
        }
        
        # 3. Запускаем тесты
        & "$vstestPath" "$testDll" /logger:trx
        
        # 4. Проверяем существование результатов
        $trxFiles = Get-ChildItem "UnitTestProject1\bin\Debug\TestResults\*.trx"
        if (-not $trxFiles) {
            throw "No test results files found!"
        }
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: Test-Results
        path: UnitTestProject1/bin/Debug/TestResults/*.trx