name: .NET Framework Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore WindowsFormsApp1.sln

      - name: Build solution
        run: msbuild WindowsFormsApp1.sln /p:Configuration=Release

      - name: Run MSTest tests
        run: |
          & 'C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe' .\TestProject1\bin\Release\TestProject1.dll