name: .NET Tests on PR

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: windows-latest  # или ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Test
      run: dotnet test --configuration Release --logger "trx;logfilename=test-results.trx"
    
    - name: Upload results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: Test-Results
        path: **/*.trx