name: .NET 8.0 CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    # Альтернативный способ запуска тестов
    - name: Run tests
      run: |
        $testDll = Get-ChildItem -Path . -Recurse -Filter "TestProject1.dll" | Where-Object { $_.FullName -like "*bin\Release\net8.0*" } | Select-Object -First 1
        if ($null -eq $testDll) {
            Write-Error "TestProject1.dll not found!"
            exit 1
        }
        Write-Host "Found test DLL at: $($testDll.FullName)"
        dotnet vstest $testDll.FullName --logger:"console;verbosity=normal"
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: TestResults/