name: .NET Tests on PR

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: windows-latest  # или ubuntu-latest для кроссплатформенных тестов

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET 8.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Disable workload updates
      run: dotnet workload update --disable-parallel

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Release --no-restore

    - name: Run tests with results
      run: |
        dotnet test --configuration Release --no-build --logger "trx;LogFileName=test-results.trx" --results-directory TestResults
        
        # Проверяем создание файла результатов (для отладки)
        ls -R TestResults

    - name: Upload test results
      uses: actions/upload-artifact@v4  # Важно использовать v4 вместо v3
      if: always()
      with:
        name: Test-Results
        path: TestResults/*.trx